' https://plantuml.com/sequence-diagram '
@startuml state_machine

[*] --> Init

state PingDecision <<choice>>
state PingDecision2 <<choice>>
state PingDecision3 <<choice>>
state SSHDecision <<choice>>

' decisions '
PingDecision --> ModbusDelay : [modbus_enabled == true]
PingDecision --> PingDecision2 : [modbus_enabled == false]

PingDecision2 --> SSHDelay : [ssh_enabled == true]
PingDecision2 --> PingDecision3 : [ssh_enabled == false]

PingDecision3 --> PsuPowerOffDelay : [psu_enabled == true]
PingDecision3 --> Setup : [psu_enabled == false]

SSHDecision --> ReverseModbusDelay : [modbus_enabled == true]
SSHDecision --> ReversePingDelay : [modbus_enabled == false]

' states '
Init --> PsuInit : [psu_enabled == true]
Init --> Setup : [psu_enabled == false]

PsuInit --> Setup : [success == true]
PsuInit --> Failure : [success == false]

SetupDelay --> Setup : [waiting_steps == total_waiting_steps]
SetupDelay --> SetupDelay : [waiting_steps != total_waiting_steps]

Setup --> PsuPowerOn : [psu_enabled == true]
Setup --> PingDelay : [psu_enabled == false]

PsuPowerOn --> PingDelay : [success == true]
PsuPowerOn --> Failure : [success == false]

PingDelay --> Ping : [waiting_steps == total_waiting_steps]
PingDelay --> PingDelay : [waiting_steps != total_waiting_steps]

PsuPowerOffDelay -> PsuPowerOff : [waiting_steps == total_waiting_steps]
PsuPowerOffDelay -> PsuPowerOffDelay : [waiting_steps != total_waiting_steps]

PsuPowerOff --> SetupDelay : [success == true]
PsuPowerOff --> Failure : [success == false]

Ping --> PingDecision : [success == true]
Ping --> Ping: [success == false]

ModbusDelay --> Modbus : [waiting_steps == total_waiting_steps]
ModbusDelay --> ModbusDelay : [waiting_steps != total_waiting_steps]

Modbus --> PingDecision2 : [success == true]
Modbus --> Failure : [success == false]

SSHDelay -> SSH : [waiting_steps == total_waiting_steps]
SSHDelay -> SSHDelay : [waiting_steps != total_waiting_steps]

SSH --> SSHDecision : [success == true]
SSH --> Failure : [success == false]

ReverseModbusDelay --> ReverseModbus : [waiting_steps == total_waiting_steps]
ReverseModbusDelay --> ReverseModbusDelay : [waiting_steps != total_waiting_steps]

ReverseModbus --> ReverseModbus : [success == false]
ReverseModbus --> ReversePingDelay : [success == true]

ReversePingDelay --> ReversePing : [waiting_steps == total_waiting_steps]
ReversePingDelay --> ReversePingDelay : [waiting_steps != total_waiting_steps]

ReversePing --> ReversePing : [success == false]
ReversePing --> Setup : [success == true]

Failure -> [*]

@enduml
