' https://plantuml.com/sequence-diagram '
@startuml state_machine

[*] --> Init

state PingDecision <<choice>>
state PingDecision2 <<choice>>
state PingDecision3 <<choice>>
state SSHDecision <<choice>>

' decisions '
PingDecision --> Modbus : [modbus_enabled == true]
PingDecision --> PingDecision2 : [modbus_enabled == false]

PingDecision2 --> SSH : [ssh_enabled == true]
PingDecision2 --> PingDecision3 : [ssh_enabled == false]

PingDecision3 --> PsuPowerOff : [psu_enabled == true]
PingDecision3 --> Setup : [psu_enabled == false]

SSHDecision --> ReverseModbus : [modbus_enabled == true]
SSHDecision --> ReversePing : [modbus_enabled == false]

' states '
Init --> PsuInit : [psu_enabled == true]
Init --> Setup : [psu_enabled == false]

PsuInit --> Setup : [success == true]
PsuInit --> Failure : [success == false]

Setup --> PsuPowerOn : [psu_enabled == true]
Setup --> Ping : [psu_enabled == false]

PsuPowerOn --> Ping : [success == true]
PsuPowerOn --> Failure : [success == false]

PsuPowerOff --> Setup : [success == true]
PsuPowerOff --> Failure : [success == false]

Ping --> PingDecision : [success == true]
Ping --> Ping: [success == false]

Modbus --> PingDecision2 : [success == true]
Modbus --> Failure : [success == false]

SSH --> SSHDecision : [success == true]
SSH --> Failure : [success == false]

ReverseModbus --> ReverseModbus : [success == false]
ReverseModbus --> ReversePing : [success == true]

ReversePing --> ReversePing : [success == false]
ReversePing --> Setup : [success == true]

@enduml
